language: php

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

matrix:
    include:
        # Oldest possible versions
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 5.6
          env: SYMFONY_LTS='^3'
        - php: 7.0
          env: SYMFONY_LTS='^2'
        - php: 7.0
          env: SYMFONY_LTS='^3'
        # Symfony 4
        - php: 7.1
        - php: 7.1
          env: SONATA='^3.6'
        - php: 7.1
          env: SONATA='dev-master'
        - php: 7.2

before_install:
  - if [ "$SYMFONY_LTS" != "" ]; then composer require --dev --no-update symfony/lts=$SYMFONY_LTS; fi
  - if [ "$SONATA" != "" ]; then composer require --dev --no-update sonata-project/doctrine-orm-admin-bundle=$SONATA; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist
  - ./phpunit install

script: ./phpunit
